### PR TITLE
chore: allow `firebase-admin` v12

### PR DESCRIPTION
**Pull request by luc122c**
The Firebase Admin SDK for Node has been [bumped to v12](https://firebase.google.com/support/release-notes/admin/node).   This currently leads to unmet peer dependency warnings:
```
 WARN  Issues with peer dependencies found
 
└─┬ nuxt-vuefire 1.0.0
  └── ✕ unmet peer firebase-admin@^11.3.0: found 12.0.0
  ```
  
  This PR adds v12 to the allowed ranges.

### CODE REVIEW

**Comment by posva** [comment]
Thanks! It looks like firebase-functions are still not supporting firebase-admin 12, so we will have to wait a bit longer. I pushed changes to actually change the peer dep (it wasn't changed)

**Comment by luc122c** [comment]
> I pushed changes to actually change the peer dep (it wasn't changed)

Oops, missed that! Thanks :)

**Comment by luc122c** [comment]
> Thanks! It looks like firebase-functions are still not supporting firebase-admin 12, so we will have to wait a bit longer. 

It looks like there is a PR tracking this: https://github.com/firebase/firebase-functions/issues/1496

**Comment by posva** [comment]
Thanks for the PR. I will locally update once the upstream issue is fixed.

**Comment by prvashisht** [comment]
@posva it was merged a few hours after you closed this :D any update on this fix?

**Comment by luc122c** [comment]
@posva Is there any chance this could be looked at again please?

**Pull request closed without merging**
