### PR TITLE
Add logo-vuefire.svg and update README.md

### PR DESCRIPTION
**Pull request by posva**

### CODE REVIEW

**Comment by posva** [comment]
Sorry, I pushed forced to master to prevent people from reading the new documentation that is still unpublished so I had to create a new PR

**Comment by posva** [comment]
I was thinking we could make the V bigger than the flame so the image has a more square-like shape. WDYT?

**Comment by posva** [comment]
oh yeah ping @geneparcellano

**Comment by geneparcellano** [comment]
@posva didn't get a chance to look into this yesterday, will probably not have time until this weekend. I'll post the updates here when I have something.

**Comment by posva** [comment]
no worries, there is no rush

**Comment by geneparcellano** [comment]
@posva I tried updating the logo, per your request, but it did not look good at all. The visual relationships of the angles and the proportions of the elements did not work. I would have to redesign the logo into something completely different to make it fit into a square. This will def take some time.

One thing I tried is change the angles a little to make the logo a little wider without breaking the visual relationships of the elements. I've pushed my changes to my fork, let me know if it's ok.

One thing I noticed, after I updated my branch it did not seem to have updated the PR. Not sure what's going on. I'll look around to see how to fix this, but let me know if you have suggestions.

**Comment by posva** [comment]
It's fine, it's not something that has to be done now, and you are free to drop at any time if you don't have the time 🙂 

What I was thinking was to have a smaller flame to make it easier to keep the aspect ratio.

You will have to open a new PR, maybe even push to a different branch. This is my bad, I push forced and messed up things. If you do I will close this PR :)

**Comment by geneparcellano** [comment]
You can close this PR, I'll open another one. Thanks.

**Pull request closed without merging**
