### PR TITLE
Adding deletion and update info

### PR DESCRIPTION
**Pull request by sadick254**
The inclusion of how to delete and update are important to help the developer to accomplish CRUD operations.

### CODE REVIEW

**Comment by chrisvfritz** [comment]
@sadick254 Deleting and updating are just done the normal Firebase way. [See the example](https://github.com/vuejs/vuefire/blob/master/examples/todo-app/index.html).

**Comment by sadick254** [comment]
I totally agree. Deleting and Updating are done the Firebase way. The main reason is to help someone who is just starting interacting with the js stack (Vuejs,Vuefire & Firebase), to at least get some ideas on how to compose his/her app.

**Comment by posva** [comment]
@sadick254 Thanks for the initiative. I'd like to update the example to fit coding style and match the example mentioned by @chrisvfritz but I cannot edit the file and add commits to the PR. Did you uncheck the _Give access_ checkbox when creating the PR?

**Comment by sadick254** [comment]
@posva  my bad i deleted my fork after making the PR i guess thats why you cant make edits.Bad thing i dont know how to reverse that. @chrisvfritz  I saw the example but the reason why i didnt want to use that is because there is a small difference between the todo app example and the example already provided on the readme.md.

**Pull request closed without merging**
