### PR TITLE
chore: update to firebase 8x

### PR DESCRIPTION
**Pull request by aperron**

### CODE REVIEW

**Comment by glemmatim** [comment]
Any idea when/if this will be merged? I just updated the Nuxt Firebase module which has firebase v8 as a requirement.

**Comment by aperron** [comment]
Hello,
to simplify review of this pull request.

summary content:

- dependency firebase in package.json `^7.2.3` -> `^8.1.1`
- `import { XXX } from 'firebase'` changed to `import firebase from 'firebase/app'`.
- versions (i'm not sure, if it's necessary):
   - @posva/vuefire-core version "2.3.3" changed to "2.3.4"
   - vuefire version "2.2.4" changed to "2.2.5"
   - vuexfire version  "3.2.4" changed to  "3.2.5"

that all.

minor:
* in firebase 8.0.0. `timestampsInSnapshots` has been remove from `FirestoreSettings`. So documentation could be clean up. see [firebase release note](https://firebase.google.com/support/release-notes/js)

**Comment by aperron** [comment]
For this PR, i trusted the tests to validate that it has no regression.
But i wanted to test in my personal project. And the result is not good.

---

My error:
    I use `bindFirestoreRef(path, ref_to_collection)`. This collection contains objects that have a Firebase document reference on a field. The function `isDocumentRef` don't detect this child like a Firebase DocumentReference (no `onSnapshot` method on child object)

I tried a quick fix:
```javascript
function isDocumentRef(o) {
    // return (o && o.onSnapshot)
    return (o && o.firestore)
}
// ...
function recursiveExtract(...){
   // ...
   if (isDocumentRef(ref)) {
       ref = ref.firestore.app.firestore().doc(ref.path)
```
This looks ok, but I don't see any changes in the Firebase release note that might explain this.

---
 
I'm not sure how to install it locally.

1. `yarn build` on the root folder of vuefire git clone
2. on my project:
    * add `yarn add @posva/vuefire-core@file://${GIT_CLONE_PATH}/vuefire/packages/@posva/vuefire-core/`
    * add `yarn add vuexfire@file://${GIT_CLONE_PATH}/vuefire/packages/vuexfire`

@postva: this installation sounds good to you or you see some side effects which may explain this error ?

@glemmatim: Could you test on your side ?

**Review by posva — CHANGES_REQUESTED** [review]
Thanks for this! Can you remove the version changes? That will be done separately.

People recently reported some bugs with Firebase 8 but there doesn't seem to be any change in the code so I think something that is mocked from Firebase has changed in v8. I'm concerned this could be a breaking change too and might need to release in a v3 of vuefire

Edit: as you mentioned, it's the `onSnapshot` function not existing anymore. Will have to do more research

**Comment by posva** [comment]
Created https://github.com/firebase/firebase-js-sdk/issues/4134 to know more about it since we don' have access to `firestore` inside of that function to create the reference and this looks like a breaking change in firebase

**Comment by posva** [comment]
Apparently it's being tracked at https://github.com/firebase/firebase-js-sdk/issues/4125

**Comment by aperron** [comment]
My last test with firebase@8.1.2 is OK. The bug without `onSnapshot` method has been fixed.

I also deleted the changes in the versions.

**Review by posva — APPROVED** [review]
Thanks!

**Comment by mfissehaye** [comment]
How can I upgrade my vuefire package to the latest that uses firebase v8

**Comment by AjahnCharles** [comment]
> How can I upgrade my vuefire package to the latest that uses firebase v8

Change the version of VueFire in `package.json` to 2.3.4

**Comment by mfissehaye** [comment]
`2.3.4` is not available. Perhaps there are new versions `3.0.0-alpha.1`. I will give that a try.

**Comment by AjahnCharles** [comment]
@mfissehaye - I see you now discovered 2.2.5! Sorry about the confusion.

For future reference, I recommend the following (instead of trusting me!) - it automatically bumps your `package.json` to the latest (non-alpha/beta) versions:
```
// Only once (to install globally)
npm i -g npm-check-updates

// Update package.json
ncu -u

// Install new versions from package.json
npm i
```

I do recommend some caution; it will update major versions (which might include breaking changes). I usually review the `git diff` before committing & discard anything that's giving me problems.

**Comment by mfissehaye** [comment]
I am still getting error `Uncaught TypeError: Cannot convert undefined or null to object` with versions updated.
```
"vuefire": "^2.2.5",
"vuexfire": "^3.2.5"
```

Here is the vuexfire code
    ```
    const currentUser = this.$fire.auth.currentUser
    if (currentUser) {
      const uid = currentUser.uid
      const carts = this.$fire.firestore.collection(`users/${uid}/carts`)

      // eslint-disable-next-line no-consoleconst currentUser = this.$fire.auth.currentUser
    if (currentUser) {
      const uid = currentUser.uid
      const carts = this.$fire.firestore.collection(`users/${uid}/carts`)
      return await context.bindFirestoreRef('carts', carts, { wait: true })
    }
```

**Pull request merged**
