### PR TITLE
fix(types): unbindFirestoreRef type

### PR DESCRIPTION
**Pull request by JFGHT**

### CODE REVIEW

**Review by posva — APPROVED** [review]
Thanks!

**Comment by JFGHT** [comment]
> Thanks!

No prob. Docs are a bit missleading regarding `reset` tho.

**Comment by JFGHT** [comment]
@posva No prob man. I think I made a mistake tho. Should not be `reset?: FirestoreOptions['reset']` instead?

**Comment by posva** [comment]
@JFGHT that's right, I just pushed a fix. Thanks!

**Pull request merged**
