### PR TITLE
Update array on bind (issue #19)

### PR DESCRIPTION
**Pull request by lunardog**
$bindAsArray fails to update if used after $unbind on the same key. Array items arrive from Firebase, but the property doesn’t show change, array looks empty.

Use case: same Vue component changes its reference during its lifetime.

### CODE REVIEW

**Comment by lunardog** [comment]
Suddenly, I'm having an "infinite watch" warning in my project. Could it be caused by the `$delete`?

**Comment by harrysbaraini** [comment]
@lunardog I am using your changes on my project, and I was having "infinite watch" too, but I found I was returning a value in my "watch" function.

**Comment by lunardog** [comment]
I think there's a danger to the use case I suggested: when we re-bind, the events stay. I added the `delete` on the reactive prop, but not on the `firebase` events for `value` and `child_*`.

Reject?

**Comment by posva** [comment]
I'm taking a look into this. There's actually an easier way than deleting the key using `Vue.delete`, I'll post a PR with more tests for it. I hope you don't mind I pick your test and modify it a bit 😄

**Comment by lunardog** [comment]
No problem, @posva. Thank you for taking care of this. I see you check if `vm[key]` is `undefined` before binding. That is indeed more elegant. 

I'll close this PR.

**Pull request closed without merging**
