### PR TITLE
[WIP] Add support for Firebase Emulators and Functions

### PR DESCRIPTION
**Pull request by akodkod**
Hi 👋 

I added support for Firebase Emulators and Functions.

There are two ways to enable emulators:

1. **Nuxt.** Just add this to `nuxt.config.ts`
```js
// nuxt.config.ts
{
  // ...
  vuefire: {
    emulators: {
      enabled: process.env.NODE_ENV !== "production",

      // Optional
      auth: {
        enabled: true,
        url: "http://localhost:9099",
        options: {
          disableWarnings: true,
        },
      },

      // Optional
      database: {
        enabled: true,
          host: "localhost",
          port: 9000,
      },

      // Optional
      firestore: {
        enabled: true,
        host: "localhost",
        port: 8080,
      },

      // Optional
      functions: {
        enabled: true,
        host: "localhost",
        port: 5001,
      },

      // Optional
      storage: {
        enabled: true,
        host: "localhost",
        port: 9199,
      },
    },
  },
  // ...
}
```

2. Using environment variables (doesn't work with Nuxt)
```js
VUEFIRE_EMULATORS_ENABLED=true // or 1, on, yes

// Optional
VUEFIRE_AUTH_EMULATOR_ENABLED=true
VUEFIRE_AUTH_EMULATOR_URL=http://localhost:9099
VUEFIRE_AUTH_EMULATOR_DISABLE_WARNINGS=true

// Optional
VUEFIRE_DATABASE_EMULATOR_ENABLED=true
VUEFIRE_DATABASE_EMULATOR_HOST=localhost
VUEFIRE_DATABASE_EMULATOR_PORT=9000

// Optional
VUEFIRE_FIRESTORE_EMULATOR_ENABLED=true
VUEFIRE_FIRESTORE_EMULATOR_HOST=localhost
VUEFIRE_FIRESTORE_EMULATOR_PORT=8080

// Optional
VUEFIRE_STORAGE_EMULATOR_ENABLED=true
VUEFIRE_STORAGE_EMULATOR_HOST=localhost
VUEFIRE_STORAGE_EMULATOR_PORT=9199

// Optional
VUEFIRE_FUNCTIONS_EMULATOR_ENABLED=true
VUEFIRE_FUNCTIONS_EMULATOR_HOST=localhost
VUEFIRE_FUNCTIONS_EMULATOR_PORT=5001
```

⚠️ At the moment this PR has one problem and I need your help to solve it. When I run `pnpm build` it throws an error, but the files compile successfully. I can include this module in my project using the pnpm local link and everything works fine. [Here is the output of `pnpm build`](https://gist.github.com/AKodkod/9de91c01ccb3240241b8f48256e31be6).

Also, I'm not sure about putting `useAppConfig` into `global.d.ts`. 

I would be happy to hear any constructive feedback.

Have a good day,
Andrew

### CODE REVIEW

**Comment by posva** [comment]
Hello! Thanks for the proposal, this is nice help!
The automatically connecting emulators should actually be nuxt plugin (or multiple ones), it shouldn't be within vuefire code because this version is not tree shakable. I think I will take quite some time to review this since I probably need to rewrite and reorganize a big part but it's really helpful and feel free to give it a try yourself.

To give some visibility, I will likely be able to check this again mid-end April

**Comment by tleperou** [comment]
Sounds pretty interesting.

What are the progress with that matter – help welcomed maybe ?

**Comment by posva** [comment]
I should be able to check this in the following months

**Comment by tleperou** [comment]
I saw this one in the template plugin of packages/nuxt

```// connectFirestoreEmulator(getFirestore(firebaseApp), 'localhost', 8080)```

would you go with the OP direction or the one in the template ?

**Comment by posva** [comment]
The build error should also go away if we move this to Nuxt 😄

**Comment by tleperou** [comment]
🚀

**Pull request closed without merging**
