### PR TITLE
feat: add new VueFire logo

### LINKED ISSUE #158: Logo suggestion
I came across this logo made by the owner of this repo: https://github.com/sejr/vuefire-quickstart
He gave his permission to use it as a logo for VueFire: https://github.com/sejr/vuefire-quickstart/issues/1

What do you think? 😎

### PR DESCRIPTION
**Pull request by sarahdayan**
This adds the new logo by @geneparcellano to the repository and documentation.

**Before**

Capture d’écran 2020-02-06 à 17 50 38

**After**

Capture d’écran 2020-02-06 à 17 50 55

fix #158

### CODE REVIEW

**Comment by posva** [comment]
Thank you!! Can we make wider and smaller in height though? It doesn't have to be squared, but similar proportions to the Firebase logo would be better

**Comment by sarahdayan** [comment]
@posva If we make it wider it will increase the height as well, unless we alter the illustration itself. I could do it but I think it's a better idea for @geneparcellano to take care of it 🙂

**Comment by posva** [comment]
I see. Yes, I want the illustration to be altered, it's too vertical right now

**Comment by geneparcellano** [comment]
I've actually tried to alter the illustration a few times and it just looked skewed. Changing it to be closer to square also changes the relationship of each shapes to each other and to the negative space around it. My thought was to completely redesign it, come up with another logo that would fit a square. I just never got around to it.

@sarahdayan If you would like to take a shot at redesigning or altering that logo, you're more than welcome to do so. I just wasn't able to come up with a better alternative and I won't have much time to do so anytime soon 😞.

**Comment by sarahdayan** [comment]
I will try take a spin at it 👍

**Comment by posva** [comment]
Thank you Sarah!

**Comment by sarahdayan** [comment]
What do you think @posva @geneparcellano? The logo is wider (not exactly a square but closer), without skewing the proportions.

vuefire

**Comment by geneparcellano** [comment]
@sarahdayan your changes gave me some ideas on how to make it even a little more square using some minor adjustments. I hope you don't mind me making some additional tweaks. Please see below.

On the left, I took your idea and adjusted the angles of the lines a little bit and moved some of the colors around.

On the right, I also changed the angles a little but kept the original configuration. I did have have to move the line on the fire a little to the right to compensate.

Let me know what you think. Also, feel free to make additional changes to these wherever you feel necessary.

image

**Comment by sarahdayan** [comment]
@geneparcellano Neaaato! I think #2 is definitely winning.

@posva ?

**Comment by posva** [comment]
I do like the one with a bigger flame more :)

**Comment by geneparcellano** [comment]
@posva @sarahdayan here's a zip with the svg file of the logo on the right. Just let me know if there's anything else I can do.
[logo-vuefire.zip](https://github.com/vuejs/vuefire/files/4176976/logo-vuefire.zip)

**Comment by sarahdayan** [comment]
Thanks @geneparcellano, I've updated the PR 🙂 This looks [badass](https://deploy-preview-589--vuefire.netlify.com/).

**Comment by geneparcellano** [comment]
That looks awesome, thank you!

**Comment by posva** [comment]
Thanks to both of you!
I wish it had rounder corners and some a bit of depth (like the Firebase one) without necessarily keeping Vue's color but it's still good and gives the project some identity :)

**Comment by sarahdayan** [comment]
@posva This can definitely be iterated on!

**Pull request merged**
