### PR TITLE
fix(nuxt): use `lodash.template` directly to compile templates

### PR DESCRIPTION
**Pull request by danielroe**
We are going to be removing support for [compiling templates from disk using `lodash.template`](https://github.com/nuxt/nuxt/issues/25332) in Nuxt v4. This is a PR to move lodash usage directly into vuefire's Nuxt module.

It would also be possible to avoid using it entirely, which I would _strongly_ recommend, either:
* using a custom function to handle the replacement, such as in https://github.com/nuxt-modules/color-mode/pull/240
* or moving the string interpolation logic directly into `getContents`

### CODE REVIEW

**Comment by santiagoaloi** [comment]
I encountered an issue while installing the `VueFire/Nuxt` module.
This problem occurs specifically when using **compatibilityVersion: 4**.

### Package Versions

```json
"@firebase/app-types": "^0.9.2",
"firebase": "^10.12.2",
"firebase-admin": "^12.2.0",
"firebase-functions": "^5.0.1"
  ```
   
   ### Environment Details

```html
- Operating System: Darwin
- Node Version:     v22.2.0
- Nuxt Version:     3.12.2
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  npm@10.7.0
- Builder:          -
- User Config:      future, modules, extends, components, vuefire
- Runtime Modules:  nuxt-vuefire@1.0.2
- Build Modules:    -
```

 ### Temporary Workaround

To address the issue temporarily, you can use the following configuration:

```js
export default defineNuxtConfig({
  future: {
    compatibilityVersion: 4,
  },

  experimental: {
    compileTemplate: true,
  },

})
```

Note: This workaround is effective for version 3 only. Version 4 will not be reversible.

 ### Additional Information

It appears that the pending merge of #1545 will resolve this compatibility conflict.

**Comment by posva** [comment]
Thank you Daniel! I should indeed migrate out from templates and split the plugin into multiple ones that are conditionally added by the module. For anybody else wanting to contribute, feel free to open a new PR that split the two plugins with an ejs extension.

**Review by posva — APPROVED** [review]

**Comment by posva** [comment]
Apparently this requires the user to install lodash-es so I think I will release once the plugins are split and no templates are used

**Comment by danielroe** [comment]
It adds lodash-es to the dependencies. Why would the user need to install it?

**Comment by posva** [comment]
I was as confused as you. Maybe it was because I tried yalc instead of using npm pack

**Comment by danielroe** [comment]
Whew. Thanks for the heads up about yalc 🙏

**Pull request merged**
